<a href="https://colab.research.google.com/github/Aryann29/AI-ML-from-scratch/blob/main/multiLinearRegression_OLS.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [53]:
import numpy as np

data = np.array([
    [850, 2, 1, 5, 10, 120],
    [1200, 3, 2, 7, 5, 95],
    [650, 1, 3, 2, 15, 55],
    [1000, 2, 4, 9, 7, 110],
    [1400, 3, 5, 12, 3, 105],
    [1300, 2, 1, 8, 6, 115],
    [900, 2, 3, 3, 8, 100],
    [1100, 3, 2, 6, 4, 90],
    [950, 1, 4, 5, 10, 95],
    [1350, 3, 5, 10, 2, 108]
])

X_train = data[:7, :5] #first 7 rows
y_train = data[:7, 5].reshape(7, 1)  # actual for 7 rows
X_test = data[7:, :5]  # 3 rows for testing
y_test = data[7:, 5].reshape(3, 1) # testing actual vals


In [55]:
X_train,y_train,X_test,y_test

(array([[ 850,    2,    1,    5,   10],
        [1200,    3,    2,    7,    5],
        [ 650,    1,    3,    2,   15],
        [1000,    2,    4,    9,    7],
        [1400,    3,    5,   12,    3],
        [1300,    2,    1,    8,    6],
        [ 900,    2,    3,    3,    8]]),
 array([[120],
        [ 95],
        [ 55],
        [110],
        [105],
        [115],
        [100]]),
 array([[1100,    3,    2,    6,    4],
        [ 950,    1,    4,    5,   10],
        [1350,    3,    5,   10,    2]]),
 array([[ 90],
        [ 95],
        [108]]))

In [59]:
class MLR:
  def __init__(self):
    self.coef = None
    self.intercept = None

  def fit(self, X_train, y_train):
    X_train = np.insert(X_train,0,1,axis=1) #inserting 1 in cols, m cols (m+1) cols

    #    (X^T X)^-1 X^T y
    betas = np.linalg.inv(np.dot(X_train.T,X_train)).dot(X_train.T).dot(y_train)
    print(betas)
    self.coef = betas[1:]
    self.intercept = betas[0]

  def predict(self,X_test):
      return np.dot(X_test,self.coef) + self.intercept
              # example if we have 3 colums + 1 extra b0 total = 4 betas ,of which 3 coef 1 intercept
              # X_test will have 3 colums and for example 4 rows to predict
              # so X test * coef  = (4,3) (3,1) => (4,1) + intercept => 4,1

In [60]:
model = MLR()

In [61]:
model.fit(X_train,y_train)

[[ 3.74163907e+02]
 [-1.38249071e-01]
 [-1.97946091e+01]
 [-1.09338010e+01]
 [ 5.68721561e+00]
 [-1.23496238e+01]]


In [67]:
model.predict(X_test)

array([[125.56329698],
       [ 84.23731537],
       [105.64773632]])

In [64]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [65]:
skModel = LinearRegression()
skModel.fit(X_train,y_train)

LinearRegression()

In [66]:
skModel.coef_,skModel.intercept_

(array([[ -0.13824907, -19.79460913, -10.93380097,   5.68721561,
         -12.34962384]]),
 array([374.16390657]))

In [68]:
skModel.predict(X_test)

array([[125.56329698],
       [ 84.23731537],
       [105.64773632]])